name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare Go environment
        uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.17.2'
      - name: Verify URLs in README.md
        run: go run verify_urls.go
