name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.17.0'
      - run: go run verify_urls.go
