name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: false
      - name: Verify URLs in README.md
        run: go run verify_urls.go
